//! AUTO-GENERATED by scripts/ts/gen-phase3-account-fixture.mjs.
//! Do not edit by hand.

pub fn phase3_account_addr() -> felt252 {
    0xacc0
}

pub fn phase3_target_addr() -> felt252 {
    0xbeef
}

pub fn phase3_chain_id() -> felt252 {
    'SN_MAIN'
}

pub fn phase3_nonce() -> felt252 {
    0x2030405060708
}

pub fn phase3_execute_after() -> u64 {
    100
}

pub fn phase3_execute_before() -> u64 {
    3000
}

pub fn phase3_pubkey_low() -> felt252 {
    0xa78ba9e812b17840f954e68f2e56b579
}

pub fn phase3_pubkey_high() -> felt252 {
    0x649604ad0b91e3e0d7be95e63a851f90
}

pub fn phase3_message_hash() -> felt252 {
    0x7dc0cb86f8a4a0010c9a4d7427f0d2aa5ed2ec5138be8bd15afa7b081b5e71b
}

pub fn phase3_set_value_selector() -> felt252 {
    0x3d7905601c217734671143d457f0db37f7f8883112abd34b92c4abfeafde0c3
}

pub fn phase3_set_value_arg() -> felt252 {
    0xCAFE
}

pub fn phase3_signature_envelope() -> Array<felt252> {
    array![
        0x56325f534e49503132, 0x0, 0x45443235353139, 0xd83ef02981c87a4ba5016a131821c16f,
        0xede87a192454694340929d3e26cf0ebf, 0x8f133fe51ab08cab8861e9711f9e2963,
        0xa4def4a6c4ae556bc91cc5b8acde751, 0x40, 0x30, 0x37, 0x64, 0x63, 0x30, 0x63, 0x62, 0x38,
        0x36, 0x66, 0x38, 0x61, 0x34, 0x61, 0x30, 0x30, 0x31, 0x30, 0x63, 0x39, 0x61, 0x34, 0x64,
        0x37, 0x34, 0x32, 0x37, 0x66, 0x30, 0x64, 0x32, 0x61, 0x61, 0x35, 0x65, 0x64, 0x32, 0x65,
        0x63, 0x35, 0x31, 0x33, 0x38, 0x62, 0x65, 0x38, 0x62, 0x64, 0x31, 0x35, 0x61, 0x66, 0x61,
        0x37, 0x62, 0x30, 0x38, 0x31, 0x62, 0x35, 0x65, 0x37, 0x31, 0x62, 0x14,
        0x5d870c6b1f8eca3e201811c6, 0x3c2f722775f29fa184188eac, 0x31ac29a78c7c5f3a, 0x0,
        0xaadffc6f798423920482fd67, 0xca93591bb642a193264e8efc, 0x7bca99a955e39f0e, 0x0,
        0x23689b347691739c1b2a4dee78c142bd, 0x1164ab58611c5e4c7b8f0d2c5e8b01249,
        0x2989fd5cd2180d019130d2c7, 0x5ad1cca72a6fda95e33aa0fe, 0x20cdd532ea80c8a0, 0x0,
        0xa7dddd1cc4d01de6f5400d6c, 0x9ba6152e2f23fe7696d4269e, 0x5f6e2688d25c3744, 0x0,
        0x3be1e2cac49011af0ef4134dd56bf03d, 0x101985a59491aa51fdaf87430e733a320,
        0xca418295d0e07639f47ff70e3b3fe75b, 0x457cc83980662196656fb7f48db729fc,
        0x9c373c4abcace38f85fced2c2d13685e, 0x504112c6a157d86dcf9420df7ced6441,
    ]
}
