//! AUTO-GENERATED by scripts/ts/gen-p256-fixture.mjs.
//! Do not edit by hand.
//!
//! Private key: 0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20
//! Signed hash: 0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
//! Pubkey X   : 515c3d6eb9e396b904d3feca7f54fdcd0cc1e997bf375dca515ad0a6c3b4035f
//! Pubkey Y   : 4536be3a50f318fbf9a5475902a221502bef0d57e08c53b2cc0a56f17d9f9354
//! r          : 1e6cf8aa045d528575f5804ab0d066276790e476755f2b45a2316f63f1b03d9e
//! s          : 066e8840e6fd20bf856e8b9d5e08341126b3e995a1af37863ada83a811183856
//!
//! noble-curves v2 does NOT return a recovery bit — the happy-path
//! test tries both y_parity candidates (0 and 1) and expects one to
//! verify. The wrong one is a useful negative fixture: it cannot
//! recover the correct pubkey, so the verifier returns false.

pub fn p256_message_hash() -> felt252 {
    0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
}

pub fn p256_pubkey() -> Array<felt252> {
    array![
        0xcc1e997bf375dca515ad0a6c3b4035f, 0x515c3d6eb9e396b904d3feca7f54fdcd,
        0x2bef0d57e08c53b2cc0a56f17d9f9354, 0x4536be3a50f318fbf9a5475902a22150,
    ]
}

pub fn p256_signature_y_parity_0() -> Array<felt252> {
    array![
        0x6790e476755f2b45a2316f63f1b03d9e, 0x1e6cf8aa045d528575f5804ab0d06627,
        0x26b3e995a1af37863ada83a811183856, 0x66e8840e6fd20bf856e8b9d5e083411, 0,
    ]
}

pub fn p256_signature_y_parity_1() -> Array<felt252> {
    array![
        0x6790e476755f2b45a2316f63f1b03d9e, 0x1e6cf8aa045d528575f5804ab0d06627,
        0x26b3e995a1af37863ada83a811183856, 0x66e8840e6fd20bf856e8b9d5e083411, 1,
    ]
}
