//! AUTO-GENERATED by scripts/ts/gen-webauthn-fixture.mjs.
//! Do not edit by hand.
//!
//! Private key:       0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20
//! SNIP-12 hash:      0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
//! Challenge (b64url): BbzWNM5GxyNL16SwlZw8Xt7tf1adz7ezPiPX4hl6Ki8
//! clientDataJSON:
//! {"type":"webauthn.get","challenge":"BbzWNM5GxyNL16SwlZw8Xt7tf1adz7ezPiPX4hl6Ki8","origin":"https://cifra.mx","crossOrigin":false}
//! challenge_offset:  36   (byte index of first base64 char)
//! authData len:      37  (flags=0x05)
//! Pubkey X:          515c3d6eb9e396b904d3feca7f54fdcd0cc1e997bf375dca515ad0a6c3b4035f
//! Pubkey Y:          4536be3a50f318fbf9a5475902a221502bef0d57e08c53b2cc0a56f17d9f9354
//! r:                 1398d1205a720fb8d3bb0bec9c8bda3df7e3bb5ef7fd6c62eeb7be26cc330702
//! s:                 663a1f99b5dccbb79a619d24956b4b61d3ec1466b43314315db06ec5a97baaaa

pub fn webauthn_message_hash() -> felt252 {
    0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
}

pub fn webauthn_pubkey() -> Array<felt252> {
    array![
        0xcc1e997bf375dca515ad0a6c3b4035f, 0x515c3d6eb9e396b904d3feca7f54fdcd,
        0x2bef0d57e08c53b2cc0a56f17d9f9354, 0x4536be3a50f318fbf9a5475902a22150,
    ]
}

pub fn webauthn_signature_envelope() -> Array<felt252> {
    // ByteArray(authenticator_data) + ByteArray(client_data_json) +
    // challenge_offset_u32 + r_low + r_high + s_low + s_high + y_parity
    array![
        // --- authenticator_data ---
        0x1, 0x1cea235b99d707117b9c3d7f4475d38006155e5ec160f4dc8d0e772e6f1bd5, 0x9e050000002a, 0x6,
        // --- client_data_json ---
        0x4, 0x7b2274797065223a22776562617574686e2e676574222c226368616c6c656e,
        0x6765223a2242627a574e4d354778794e4c313653776c5a7738587437746631,
        0x61647a37657a5069505834686c364b6938222c226f726967696e223a226874,
        0x7470733a2f2f63696672612e6d78222c2263726f73734f726967696e223a66, 0x616c73657d,
        0x5, // --- challenge_offset ---
        0x24, // --- r, s, y_parity ---
        0xf7e3bb5ef7fd6c62eeb7be26cc330702, 0x1398d1205a720fb8d3bb0bec9c8bda3d,
        0xd3ec1466b43314315db06ec5a97baaaa, 0x663a1f99b5dccbb79a619d24956b4b61, 0,
    ]
}

/// Same envelope with the challenge offset shifted by one byte — the
/// substring at that offset no longer base64url-decodes to the
/// message_hash, so the verifier MUST return false.
pub fn webauthn_signature_envelope_wrong_offset() -> Array<felt252> {
    array![
        0x1, 0x1cea235b99d707117b9c3d7f4475d38006155e5ec160f4dc8d0e772e6f1bd5, 0x9e050000002a, 0x6,
        0x4, 0x7b2274797065223a22776562617574686e2e676574222c226368616c6c656e,
        0x6765223a2242627a574e4d354778794e4c313653776c5a7738587437746631,
        0x61647a37657a5069505834686c364b6938222c226f726967696e223a226874,
        0x7470733a2f2f63696672612e6d78222c2263726f73734f726967696e223a66, 0x616c73657d, 0x5, 0x25,
        0xf7e3bb5ef7fd6c62eeb7be26cc330702, 0x1398d1205a720fb8d3bb0bec9c8bda3d,
        0xd3ec1466b43314315db06ec5a97baaaa, 0x663a1f99b5dccbb79a619d24956b4b61, 0,
    ]
}

/// Envelope with UP flag cleared — authenticator_data[32] becomes
/// 0x04 (UV only). The verifier MUST reject per WebAuthn §7.2 step 17.
pub fn webauthn_signature_envelope_no_up() -> Array<felt252> {
    // Rebuild the first full-word of authData with flags byte cleared.
    // Easier and cheaper to just zero the flags byte by rebuilding the
    // first full word — the fixture generator emits it pre-patched.
    array![
        0x1, 0x1cea235b99d707117b9c3d7f4475d38006155e5ec160f4dc8d0e772e6f1bd5, 0x9e040000002a, 0x6,
        0x4, 0x7b2274797065223a22776562617574686e2e676574222c226368616c6c656e,
        0x6765223a2242627a574e4d354778794e4c313653776c5a7738587437746631,
        0x61647a37657a5069505834686c364b6938222c226f726967696e223a226874,
        0x7470733a2f2f63696672612e6d78222c2263726f73734f726967696e223a66, 0x616c73657d, 0x5, 0x24,
        0xf7e3bb5ef7fd6c62eeb7be26cc330702, 0x1398d1205a720fb8d3bb0bec9c8bda3d,
        0xd3ec1466b43314315db06ec5a97baaaa, 0x663a1f99b5dccbb79a619d24956b4b61, 0,
    ]
}
