//! AUTO-GENERATED by scripts/ts/regen-ed25519-fixtures.mjs
//! Do not edit by hand. Re-run the generator if the Ed25519 verifier
//! class or Garaga hint layout changes.
//!
//! Private key: 0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20
//! Pubkey    : 79b5562e8fe654f94078b112e8a98ba7901f853ae695bed7e0e3910bad049664
//! Message   : 05bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
//! Signature : R=6ba9cc7096f6a44d9d71bbb24497cff58594a821f17c6c7354b1cd23a5efb2d8
//!             s=244d9e15cb479f7ee7145e91f8202e37840055c5cea06f67414f89890dacc605

pub fn fixture_message_hash() -> felt252 {
    0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
}

pub fn fixture_pubkey_low() -> felt252 {
    0xa78ba9e812b17840f954e68f2e56b579
}

pub fn fixture_pubkey_high() -> felt252 {
    0x649604ad0b91e3e0d7be95e63a851f90
}

pub fn fixture_signature_envelope() -> Array<felt252> {
    array![
        0xf5cf9744b2bb719d4da4f69670cca96b, 0xd8b2efa523cdb154736c7cf121a89485,
        0x372e20f8915e14e77e9f47cb159e4d24, 0x5c6ac0d89894f41676fa0cec5550084, 0x40, 0x30, 0x35,
        0x62, 0x63, 0x64, 0x36, 0x33, 0x34, 0x63, 0x65, 0x34, 0x36, 0x63, 0x37, 0x32, 0x33, 0x34,
        0x62, 0x64, 0x37, 0x61, 0x34, 0x62, 0x30, 0x39, 0x35, 0x39, 0x63, 0x33, 0x63, 0x35, 0x65,
        0x64, 0x65, 0x65, 0x64, 0x37, 0x66, 0x35, 0x36, 0x39, 0x64, 0x63, 0x66, 0x62, 0x37, 0x62,
        0x33, 0x33, 0x65, 0x32, 0x33, 0x64, 0x37, 0x65, 0x32, 0x31, 0x39, 0x37, 0x61, 0x32, 0x61,
        0x32, 0x66, 0x14, 0x8bf6bfd061a8730fb27bea39, 0x3b4c647b2d475bbc7919c26, 0x502cb3a5a5aa38a1,
        0x0, 0x1d8ffccadbbdd12daa275cff, 0xb1484d7b46bb11751549c7ee, 0x94637279d178649, 0x0,
        0x1285dde38c59c5579b1932dcd1b57f14, 0xb7b82e865e33c58e894cd2d6790513d,
        0x9d38519ab0ddbb752fc471fe, 0x4f187172c04399da28daac08, 0x5688f2b0700982ce, 0x0,
        0x8159ea18924143bb995435e5, 0x97ee113ec9761e81d4039c31, 0x21c9877dd9d3db15, 0x0,
        0x1ba0410c615d712d7fa8fd42578c78d, 0x1e5ba10ec66f9ca05fd11f302c45cb90,
        0x65cf2e70aaea7be7cd97234cce67f1db, 0x7d8dcb5cfef21ba8d0e4345eb1de8d53,
        0x9c373c4abcace38f85fced2c2d13685e, 0x504112c6a157d86dcf9420df7ced6441,
    ]
}
