//! AUTO-GENERATED by scripts/ts/gen-eip191-fixture.mjs.
//! Do not edit by hand. Re-run if the EIP-191 verifier or fixture
//! inputs change.
//!
//! Recipe matches ethers `Wallet.signMessage(bytes)` and MetaMask
//! `personal_sign` — identical bytes-on-the-wire, identical hash.
//!
//! Private key: 0x0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20
//! Signed hash: 0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
//!  (wallet side computes keccak256("\x19Ethereum Signed Message:\n32"
//!   || hash_be_32) and signs that)
//! Pubkey X   : 84bf7562262bbd6940085748f3be6afa52ae317155181ece31b66351ccffa4b0
//! Pubkey Y   : 8cc43d63b2859d469fee15f31c9edb5324266e6fd0407e87382d60fc4511acd8
//! r          : 7ee521432a511441926a07e495a0016f540eebef7dc1572e5d7f429522334d36
//! s          : 6cad2c6b8577ed622a965f1cae106a99ef490c9af86156b20176779c1cce26bd
//! v          : 27  (y_parity = 0)

pub fn eip191_message_hash() -> felt252 {
    0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
}

pub fn eip191_pubkey() -> Array<felt252> {
    array![
        0x52ae317155181ece31b66351ccffa4b0, 0x84bf7562262bbd6940085748f3be6afa,
        0x24266e6fd0407e87382d60fc4511acd8, 0x8cc43d63b2859d469fee15f31c9edb53,
    ]
}

pub fn eip191_signature() -> Array<felt252> {
    array![
        0x540eebef7dc1572e5d7f429522334d36, 0x7ee521432a511441926a07e495a0016f,
        0xef490c9af86156b20176779c1cce26bd, 0x6cad2c6b8577ed622a965f1cae106a99, 0x0,
    ]
}
