//! AUTO-GENERATED by scripts/ts/gen-secp256k1-fixture.mjs.
//! Do not edit by hand.
//!
//! Private key: 0x0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20
//! Signed hash: 0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
//! Pubkey X   : 84bf7562262bbd6940085748f3be6afa52ae317155181ece31b66351ccffa4b0
//! Pubkey Y   : 8cc43d63b2859d469fee15f31c9edb5324266e6fd0407e87382d60fc4511acd8
//! r          : 0x4e63a4ca733205851fc9884e0d230d0a077fc46b2b029f2b8362ad9a68b963ab
//! s          : 0x3a8fe8c16ee56382624fad3f65a36d9b292d617d0b639a58ddf79c047a01e95c
//! y_parity   : 1

pub fn secp256k1_message_hash() -> felt252 {
    0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
}

pub fn secp256k1_pubkey() -> Array<felt252> {
    array![
        0x52ae317155181ece31b66351ccffa4b0, 0x84bf7562262bbd6940085748f3be6afa,
        0x24266e6fd0407e87382d60fc4511acd8, 0x8cc43d63b2859d469fee15f31c9edb53,
    ]
}

pub fn secp256k1_signature() -> Array<felt252> {
    array![
        0x77fc46b2b029f2b8362ad9a68b963ab, 0x4e63a4ca733205851fc9884e0d230d0a,
        0x292d617d0b639a58ddf79c047a01e95c, 0x3a8fe8c16ee56382624fad3f65a36d9b, 0x1,
    ]
}
