//! AUTO-GENERATED by scripts/ts/gen-eip712-fixture.mjs.
//! Do not edit by hand. Re-run if domain shape, struct shape, or
//! fixture inputs change.
//!
//! Recipe matches ethers `Wallet.signTypedData(domain, types, value)`,
//! which is exactly what MetaMask `eth_signTypedData_v4` returns.
//!
//! Test conditions the Cairo test MUST cheat to:
//!   chain_id      = 0
//!   account_addr  = 0x1d6e (deploy_at this address)
//!
//! Domain   : Shhh v1 on chain 0 with salt = 0x1d6e
//! Struct   : MessageHash{hash: 0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f}
//! Final h  : 0xc59fd2836fbdcd9f28c029f191a70fe8ecb5501206d4c5de70825b7505ca9093
//! Pubkey X : 84bf7562262bbd6940085748f3be6afa52ae317155181ece31b66351ccffa4b0
//! Pubkey Y : 8cc43d63b2859d469fee15f31c9edb5324266e6fd0407e87382d60fc4511acd8
//! r        : 85de37a23956c57c8d1911e88975755857b22ff685d360faea57afb30386c747
//! s        : 77ab8c1dc3b0f52179e296c61ba4322d87353de6cac23d67cd360beeb4fca997
//! v        : 28  (y_parity = 1)

pub fn eip712_message_hash() -> felt252 {
    0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
}

pub fn eip712_account_address() -> felt252 {
    0x1d6e
}

pub fn eip712_chain_id() -> felt252 {
    0
}

pub fn eip712_pubkey() -> Array<felt252> {
    array![
        0x52ae317155181ece31b66351ccffa4b0, 0x84bf7562262bbd6940085748f3be6afa,
        0x24266e6fd0407e87382d60fc4511acd8, 0x8cc43d63b2859d469fee15f31c9edb53,
    ]
}

pub fn eip712_signature() -> Array<felt252> {
    array![
        0x57b22ff685d360faea57afb30386c747, 0x85de37a23956c57c8d1911e889757558,
        0x87353de6cac23d67cd360beeb4fca997, 0x77ab8c1dc3b0f52179e296c61ba4322d, 0x1,
    ]
}
