//! AUTO-GENERATED by scripts/ts/gen-jwt-es256-fixture.mjs.
//! Do not edit by hand. Re-run if the JWT shape, fixture inputs,
//! or envelope layout change.
//!
//! Private key: 0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20
//! Signed hash: 0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
//! Header b64 : eyJhbGciOiJFUzI1NiIsImtpZCI6InRlc3Qta2V5LTEifQ
//! Payload    :
//! {"iss":"https://appleid.apple.com","aud":"io.cifra.app","exp":9999999999,"iat":1714521600,"sub":"001234.abcdef.5678","nonce":"BbzWNM5GxyNL16SwlZw8Xt7tf1adz7ezPiPX4hl6Ki8","email":"user@privaterelay.appleid.com"}
//! Payload b64:
//! eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiaW8uY2lmcmEuYXBwIiwiZXhwIjo5OTk5OTk5OTk5LCJpYXQiOjE3MTQ1MjE2MDAsInN1YiI6IjAwMTIzNC5hYmNkZWYuNTY3OCIsIm5vbmNlIjoiQmJ6V05NNUd4eU5MMTZTd2xadzhYdDd0ZjFhZHo3ZXpQaVBYNGhsNktpOCIsImVtYWlsIjoidXNlckBwcml2YXRlcmVsYXkuYXBwbGVpZC5jb20ifQ
//! nonce_offset (in decoded JSON): 126 iss_offset   (in decoded JSON): 8
//! r          : a98dd0fc87f6f8f6ef02c62b070a7b14b4696ea8f26de9b177a054638917cbc6
//! s          : 3073b5866ae21a462b49a11012acb9f987d08283e4ab3e709e0292e1eb4755b3

pub fn jwt_message_hash() -> felt252 {
    0x5bcd634ce46c7234bd7a4b0959c3c5edeed7f569dcfb7b33e23d7e2197a2a2f
}

pub fn jwt_pubkey() -> Array<felt252> {
    array![
        0xcc1e997bf375dca515ad0a6c3b4035f, 0x515c3d6eb9e396b904d3feca7f54fdcd,
        0x2bef0d57e08c53b2cc0a56f17d9f9354, 0x4536be3a50f318fbf9a5475902a22150,
    ]
}

pub fn jwt_signature_envelope() -> Array<felt252> {
    array![
        // --- header_b64 (ByteArray) ---
        0x1, 0x65794a68624763694f694a46557a49314e694973496d74705a434936496e52,
        0x6c63335174613256354c5445696651, 0xf, // --- payload_decoded (ByteArray) ---
        0x6,
        0x7b22697373223a2268747470733a2f2f6170706c6569642e6170706c652e63,
        0x6f6d222c22617564223a22696f2e63696672612e617070222c22657870223a,
        0x393939393939393939392c22696174223a313731343532313630302c227375,
        0x62223a223030313233342e6162636465662e35363738222c226e6f6e636522,
        0x3a2242627a574e4d354778794e4c313653776c5a773858743774663161647a,
        0x37657a5069505834686c364b6938222c22656d61696c223a22757365724070,
        0x72697661746572656c61792e6170706c6569642e636f6d227d,
        0x19, // --- nonce_offset, iss_offset ---
        0x7e, 0x8, // --- r, s, y_parity ---
        0xb4696ea8f26de9b177a054638917cbc6, 0xa98dd0fc87f6f8f6ef02c62b070a7b14,
        0x87d08283e4ab3e709e0292e1eb4755b3, 0x3073b5866ae21a462b49a11012acb9f9, 0,
    ]
}

/// Tampered fixture: payload claims a different issuer. Signature is
/// re-signed for consistency, so ECDSA verifies — the verifier MUST
/// reject because the iss bytes don't match the hardcoded constant.
pub fn jwt_signature_envelope_wrong_issuer() -> Array<felt252> {
    array![
        0x1, 0x65794a68624763694f694a46557a49314e694973496d74705a434936496e52,
        0x6c63335174613256354c5445696651, 0xf, 0x6,
        0x7b22697373223a2268747470733a2f2f6578616d706c652e636f6d2f6f6175,
        0x7468222c22617564223a22696f2e63696672612e617070222c22657870223a,
        0x393939393939393939392c22696174223a313731343532313630302c227375,
        0x62223a223030313233342e6162636465662e35363738222c226e6f6e636522,
        0x3a2242627a574e4d354778794e4c313653776c5a773858743774663161647a,
        0x37657a5069505834686c364b6938222c22656d61696c223a22757365724070,
        0x72697661746572656c61792e6170706c6569642e636f6d227d, 0x19, 0x7e, 0x8,
        0x8f436e04952d1d7b9d4622ced7f35aea, 0xdded3bd7c376a7e7061ba33131bf4c92,
        0x4461920334bdeb6b27aa696feb78b9dc, 0x8e88cd13ecf92d338d25a530ece8606, 0,
    ]
}

/// Tampered fixture: payload claims a different nonce (Apple-style
/// JWT but the challenge field is for a different hash). ECDSA verifies
/// because we re-signed; verifier MUST reject because the nonce bytes
/// don't match base64url(message_hash).
pub fn jwt_signature_envelope_wrong_nonce() -> Array<felt252> {
    array![
        0x1, 0x65794a68624763694f694a46557a49314e694973496d74705a434936496e52,
        0x6c63335174613256354c5445696651, 0xf, 0x6,
        0x7b22697373223a2268747470733a2f2f6170706c6569642e6170706c652e63,
        0x6f6d222c22617564223a22696f2e63696672612e617070222c22657870223a,
        0x393939393939393939392c22696174223a313731343532313630302c227375,
        0x62223a223030313233342e6162636465662e35363738222c226e6f6e636522,
        0x3a227171717171717171717171717171717171717171717171717171717171,
        0x717171717171717171717171716f222c22656d61696c223a22757365724070,
        0x72697661746572656c61792e6170706c6569642e636f6d227d, 0x19, 0x7e, 0x8,
        0x72b950cadfb24e88efc2c83f8da51673, 0xc0524a4d44246fe3d7357659ddb05da7,
        0xd2de80dd011933272731c8b9402f98c7, 0x6c41dbfb35e1c19f7c050f19b2383ab1, 0,
    ]
}
