use shhh_wallet::ed25519::interface::{IShhhWalletDispatcher, IShhhWalletDispatcherTrait};
use shhh_wallet::outside_execution::{ISRC9_V2Dispatcher, ISRC9_V2DispatcherTrait, OutsideExecution};
use snforge_std::{
    ContractClassTrait, DeclareResultTrait, declare, start_cheat_block_timestamp_global,
    start_cheat_caller_address, start_cheat_chain_id_global,
};
use starknet::ContractAddress;
use starknet::account::Call;

// Owner pubkey as LE u256 halves (matches garaga Py_twisted format).
const PUBKEY_LOW: felt252 = 0xfedcba0987654321;
const PUBKEY_HIGH: felt252 = 0x1234567890abcdef;

fn deploy_wallet() -> (ContractAddress, IShhhWalletDispatcher) {
    let contract = declare("ShhhWallet").unwrap().contract_class();
    let mut calldata: Array<felt252> = array![PUBKEY_LOW, PUBKEY_HIGH];
    let (addr, _) = contract.deploy(@calldata).unwrap();
    (addr, IShhhWalletDispatcher { contract_address: addr })
}

// ============================================================
// SNIP-9 (Outside Execution) Tests — pre-signature checks
// ============================================================

fn make_src9_dispatcher(addr: ContractAddress) -> ISRC9_V2Dispatcher {
    ISRC9_V2Dispatcher { contract_address: addr }
}

#[test]
fn test_initial_state() {
    let (_, dispatcher) = deploy_wallet();
    let (low, high) = dispatcher.get_owner();
    assert(low == PUBKEY_LOW, 'bad pubkey low');
    assert(high == PUBKEY_HIGH, 'bad pubkey high');
}

#[test]
fn test_nonce_availability() {
    let (addr, _) = deploy_wallet();
    let src9 = make_src9_dispatcher(addr);
    assert(src9.is_valid_outside_execution_nonce(42), 'nonce should be available');
}

#[test]
#[should_panic(expected: 'SRC9: too early')]
fn test_outside_execution_too_early() {
    let (addr, _) = deploy_wallet();
    start_cheat_block_timestamp_global(500);
    let src9 = make_src9_dispatcher(addr);

    let target: ContractAddress = 0xBEEF.try_into().unwrap();
    let oe = OutsideExecution {
        caller: 'ANY_CALLER'.try_into().unwrap(),
        nonce: 1,
        execute_after: 600,
        execute_before: 2000,
        calls: array![
            Call { to: target, selector: selector!("get_owner"), calldata: array![].span() },
        ]
            .span(),
    };
    src9.execute_from_outside_v2(oe, array![0x1, 0x2].span());
}

#[test]
#[should_panic(expected: 'SRC9: too late')]
fn test_outside_execution_too_late() {
    let (addr, _) = deploy_wallet();
    start_cheat_block_timestamp_global(500);
    let src9 = make_src9_dispatcher(addr);

    let target: ContractAddress = 0xBEEF.try_into().unwrap();
    let oe = OutsideExecution {
        caller: 'ANY_CALLER'.try_into().unwrap(),
        nonce: 1,
        execute_after: 0,
        execute_before: 400,
        calls: array![
            Call { to: target, selector: selector!("get_owner"), calldata: array![].span() },
        ]
            .span(),
    };
    src9.execute_from_outside_v2(oe, array![0x1, 0x2].span());
}

#[test]
#[should_panic(expected: 'SRC9: invalid caller')]
fn test_outside_execution_wrong_caller() {
    let (addr, _) = deploy_wallet();
    start_cheat_block_timestamp_global(500);

    let caller: ContractAddress = 0x5555.try_into().unwrap();
    start_cheat_caller_address(addr, caller);

    let src9 = make_src9_dispatcher(addr);
    let expected_caller: ContractAddress = 0x9999.try_into().unwrap();
    let target: ContractAddress = 0xBEEF.try_into().unwrap();
    let oe = OutsideExecution {
        caller: expected_caller,
        nonce: 1,
        execute_after: 0,
        execute_before: 2000,
        calls: array![
            Call { to: target, selector: selector!("get_owner"), calldata: array![].span() },
        ]
            .span(),
    };
    src9.execute_from_outside_v2(oe, array![0x1, 0x2].span());
}

// ============================================================
// SNIP-9 Ed25519 signature tests — Garaga fixtures
// ============================================================
//
// Test keypair: 32 bytes of 0x42 (deterministic).
// OE: caller='ANY_CALLER', nonce=42, execute_after=0, execute_before=1000, calls=[]
// Contract address: 0xDEAD (deployed via deploy_at)
// Chain ID: 0x0 (snforge test VM default)
//
// Post-audit M-1: `caller=0` is rejected, so V7's legacy fixture was
// retired. The replacement is regenerated by
// `scripts/ts/regen-v7-oe-fixture.mjs` — re-run it whenever the V7
// encoding, the fixture inputs, or the Garaga hint layout changes.

use super::v7_oe_fixture::{v7_test_eddsa_signature, v7_test_pubkey_high, v7_test_pubkey_low};

const TEST_CONTRACT_ADDR: felt252 = 0xDEAD;

fn deploy_wallet_at_fixed_addr() -> (ContractAddress, ISRC9_V2Dispatcher) {
    let contract = declare("ShhhWallet").unwrap().contract_class();
    let calldata: Array<felt252> = array![v7_test_pubkey_low(), v7_test_pubkey_high()];
    let target: ContractAddress = TEST_CONTRACT_ADDR.try_into().unwrap();
    let (addr, _) = contract.deploy_at(@calldata, target).unwrap();
    (addr, ISRC9_V2Dispatcher { contract_address: addr })
}

/// V7 positive-path OE flow. Fixture regenerated for the post-M-1
/// `caller='ANY_CALLER'` convention by
/// `scripts/ts/regen-v7-oe-fixture.mjs`.
#[test]
fn test_outside_execution_valid_ed25519() {
    let (_addr, src9) = deploy_wallet_at_fixed_addr();
    start_cheat_block_timestamp_global(500);
    start_cheat_chain_id_global(0);
    assert(src9.is_valid_outside_execution_nonce(42), 'nonce should be available');

    let oe = OutsideExecution {
        caller: 'ANY_CALLER'.try_into().unwrap(),
        nonce: 42,
        execute_after: 0,
        execute_before: 1000,
        calls: array![].span(),
    };
    let signature = v7_test_eddsa_signature();
    let results = src9.execute_from_outside_v2(oe, signature.span());
    assert(results.len() == 0, 'should have 0 results');
    assert(!src9.is_valid_outside_execution_nonce(42), 'nonce should be used');
}

/// Negative: wrong pubkey in storage → Garaga verifier rejects the
/// otherwise-valid signature because Py_twisted no longer matches.
#[test]
#[should_panic(expected: 'SRC9: invalid signature')]
fn test_outside_execution_wrong_owner() {
    // Deploy with a DIFFERENT pubkey than what's in the signature.
    // Garaga v1.0+: Py comes from storage, so wrong pubkey → invalid signature.
    let contract = declare("ShhhWallet").unwrap().contract_class();
    let calldata: Array<felt252> = array![0xAAAA, 0xBBBB // wrong pubkey
    ];
    let target: ContractAddress = TEST_CONTRACT_ADDR.try_into().unwrap();
    let (_, _) = contract.deploy_at(@calldata, target).unwrap();
    let src9 = ISRC9_V2Dispatcher { contract_address: target };

    start_cheat_block_timestamp_global(500);
    start_cheat_chain_id_global(0);

    let oe = OutsideExecution {
        caller: 'ANY_CALLER'.try_into().unwrap(),
        nonce: 42,
        execute_after: 0,
        execute_before: 1000,
        calls: array![].span(),
    };

    // Signature was created by TEST_PUBKEY but contract stores 0xAAAA/0xBBBB
    let signature = v7_test_eddsa_signature();
    src9.execute_from_outside_v2(oe, signature.span());
}

/// Negative: replay the same OE twice. The second submission must
/// revert with 'SRC9: duplicate nonce' — this is the V7 analogue of
/// `account_nonce_replay.cairo` for the post-regeneration fixture.
#[test]
#[should_panic(expected: 'SRC9: duplicate nonce')]
fn test_outside_execution_ed25519_replay() {
    let (_, src9) = deploy_wallet_at_fixed_addr();
    start_cheat_block_timestamp_global(500);
    start_cheat_chain_id_global(0);

    let oe1 = OutsideExecution {
        caller: 'ANY_CALLER'.try_into().unwrap(),
        nonce: 42,
        execute_after: 0,
        execute_before: 1000,
        calls: array![].span(),
    };
    let sig1 = v7_test_eddsa_signature();
    src9.execute_from_outside_v2(oe1, sig1.span());

    // Replay with same nonce — should fail
    let oe2 = OutsideExecution {
        caller: 'ANY_CALLER'.try_into().unwrap(),
        nonce: 42,
        execute_after: 0,
        execute_before: 1000,
        calls: array![].span(),
    };
    let sig2 = v7_test_eddsa_signature();
    src9.execute_from_outside_v2(oe2, sig2.span());
}

// Verify Poseidon hash compatibility with starknet.js
#[test]
fn test_poseidon_hash_compatibility() {
    let result = core::poseidon::poseidon_hash_span(array![0].span());
    assert(
        result == 0x545d6f7d28a8a398e543948be5a026af60c4dea482867a6eeb2525b35d1e1e1,
        'poseidon mismatch',
    );
}
